/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package human_resources.view;

import com.github.lgooddatepicker.components.DatePickerSettings;
import com.github.lgooddatepicker.components.DateTimePicker;
import com.github.lgooddatepicker.components.TimePicker;
import com.github.lgooddatepicker.components.TimePickerSettings;
import com.github.lgooddatepicker.components.TimePickerSettings.TimeIncrement;
import com.github.lgooddatepicker.optionalusertools.PickerUtilities;
import human_resources.controller.ProcessingApplicant;
import human_resources.controller.ProcessingJobApplication;
import human_resources.controller.ProcessingJobPosition;
import human_resources.model.Applicant;
import human_resources.model.JobApplication;
import human_resources.model.JobPosition;
import human_resources.utility.JelenaException;
import human_resources.utility.Utility;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Jelena
 */
public class FormJobApplications extends JelenaView<JobApplication> {

    /**
     * Creates new form FormJobApplication
     */
    private ProcessingJobApplication processing;

    public FormJobApplications() {
        initComponents();
        processing = new ProcessingJobApplication();
        setTitle(Utility.getNameOfApplication() + " Job applications");
        btnSearch.setText("\uD83D\uDD0D");
        DatePickerSettings dtps = new DatePickerSettings(new Locale("hr", "HR"));
        TimePickerSettings timeSettings = new TimePickerSettings();
        dtps.setFormatForDatesCommonEra("dd.MM.yyyy.");
        timeSettings.use24HourClockFormat();

        dtpDateAndTimeOfReceive.datePicker.setSettings(dtps);
        dtpDateAndTimeOfReceive.datePicker.setDateToToday();
        dtpDateAndTimeOfReceive.timePicker.setTimeToNow();

        loadApplicants();
        loadJobPositions();

        load();

    }

    protected void load() {
        DefaultListModel<JobApplication> model = new DefaultListModel<>();

        processing.getEntitys(txtCondition.getText().trim()).forEach(
                (jobApplication) -> {
                    model.addElement(jobApplication);
                });
        List.setModel(model);
        List.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDateAndTimeOfReceive = new javax.swing.JLabel();
        lblNumberOfApplication = new javax.swing.JLabel();
        txtNumberOfApplication = new javax.swing.JTextField();
        cmbApplicants = new javax.swing.JComboBox<>();
        lblApplicant = new javax.swing.JLabel();
        lblJobPosition = new javax.swing.JLabel();
        cmbJobPositions = new javax.swing.JComboBox<>();
        dtpDateAndTimeOfReceive = new com.github.lgooddatepicker.components.DateTimePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtCondition = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 460));
        setPreferredSize(new java.awt.Dimension(550, 360));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 2, 14))); // NOI18N

        lblDateAndTimeOfReceive.setText("Date and time of receive:");
        lblDateAndTimeOfReceive.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        lblNumberOfApplication.setText("Number of application:");
        lblNumberOfApplication.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        txtNumberOfApplication.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N

        lblApplicant.setText("Applicant:");
        lblApplicant.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        lblJobPosition.setText("Job position:");
        lblJobPosition.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        dtpDateAndTimeOfReceive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateAndTimeOfReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtpDateAndTimeOfReceive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumberOfApplication)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblApplicant)
                                .addGap(34, 34, 34)
                                .addComponent(cmbApplicants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumberOfApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJobPosition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbJobPositions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbApplicants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApplicant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJobPosition)
                    .addComponent(cmbJobPositions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lblDateAndTimeOfReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtpDateAndTimeOfReceive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberOfApplication)
                    .addComponent(txtNumberOfApplication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        List.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        List.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(List);

        btnAdd.setText("Add");
        btnAdd.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtCondition.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N

        btnSearch.setText("S");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        JobApplication ja = new JobApplication();

        if (dtpDateAndTimeOfReceive.getDateTimeStrict() != null) {
            Date d = Utility.convertToDateViaSqlTimestamp(dtpDateAndTimeOfReceive.getDateTimeStrict());

            ja.setDateAndTimeOfReceive(d);
        }

        try {
            ja.setNumberOfApplication(Integer.parseInt(txtNumberOfApplication.getText()));
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "You need to enter number");
            return;
        }

        save(ja);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (txtCondition.getText().trim().length() < 1) {
            JOptionPane.showMessageDialog(null, "Minimum 1 characters");
            return;
        }
        load();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        JobApplication ja = List.getSelectedValue();
        if (ja == null) {
            JOptionPane.showMessageDialog(null, "First choose item");
            return;
        }
        if (JOptionPane.showConfirmDialog(
                null,
                "Safe to delete" + " " + ja.getNumberOfApplication(),
                "Delete job application",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE)
                == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            processing.delete(ja);
        } catch (JelenaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }

        load();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        JobApplication ja = List.getSelectedValue();
        if (ja == null) {
            JOptionPane.showMessageDialog(null, "First choose item");
            return;
        }
        save(ja);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void ListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }
        JobApplication ja = List.getSelectedValue();
        if (ja == null) {
            return;
        }
        setValues(ja);
    }//GEN-LAST:event_ListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<JobApplication> List;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Applicant> cmbApplicants;
    private javax.swing.JComboBox<JobPosition> cmbJobPositions;
    private com.github.lgooddatepicker.components.DateTimePicker dtpDateAndTimeOfReceive;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApplicant;
    private javax.swing.JLabel lblDateAndTimeOfReceive;
    private javax.swing.JLabel lblJobPosition;
    private javax.swing.JLabel lblNumberOfApplication;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtNumberOfApplication;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void save(JobApplication ja) {
        if (!control(ja)) {
            return;

        }
        ja.setApplicant((Applicant) cmbApplicants.getSelectedItem());
        ja.setJobposition((JobPosition) cmbJobPositions.getSelectedItem());
        ja.setDateAndTimeOfReceive(ja.getDateAndTimeOfReceive());
        ja.setNumberOfApplication(Integer.parseInt(txtNumberOfApplication.getText()));

        try {
            processing.save(ja);
        } catch (JelenaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }

        load();
    }

    @Override
    protected boolean control(JobApplication ja) {
        return controlDateAndTimeOfReceive(ja)
                && controlNumberOfApplication(ja);
    }

    @Override
    protected void setValues(JobApplication ja) {
        cmbApplicants.setSelectedItem(ja.getApplicant());
        cmbJobPositions.setSelectedItem(ja.getJobposition());
        dtpDateAndTimeOfReceive.setDateTimeStrict(Utility.convertToLocalDateTimeViaInstant(ja.getDateAndTimeOfReceive()));
        txtNumberOfApplication.setText(ja.getNumberOfApplication() == null ? ""
                : ja.getNumberOfApplication().toString());

    }

    private boolean controlDateAndTimeOfReceive(JobApplication ja) {
        if (dtpDateAndTimeOfReceive.getDateTimeStrict() == null) {
            JOptionPane.showMessageDialog(null, "Selection of date of receive is mandatory");
            return false;
        }
        ja.setDateAndTimeOfReceive(Utility.convertToDateViaSqlTimestamp(dtpDateAndTimeOfReceive.getDateTimeStrict()));
        return true;
    }

    private boolean controlNumberOfApplication(JobApplication ja) {
        if (txtNumberOfApplication.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Number of application is mandatory");
            return false;
        }
        ja.setNumberOfApplication(ja.getNumberOfApplication());
        return true;
    }

    private void loadApplicants() {

        DefaultComboBoxModel<Applicant> m = new DefaultComboBoxModel<>();
        Applicant a = new Applicant();
        a.setId(0);
        a.setFirstName("Choose");
        a.setLastName("Applicant");
        m.addElement(a);

        new ProcessingApplicant().getEntitys().forEach((applicant) -> {
            m.addElement(applicant);
        });
        cmbApplicants.setModel(m);

    }

    private void loadJobPositions() {

        DefaultComboBoxModel<JobPosition> m = new DefaultComboBoxModel<>();
        JobPosition jp = new JobPosition();
        jp.setId(0);
        jp.setNameOfJobPosition("Choose job position");

        m.addElement(jp);

        new ProcessingJobPosition().getEntitys().forEach((jobPosition) -> {
            m.addElement(jobPosition);
        });
        cmbJobPositions.setModel(m);

    }

}
