/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package human_resources.view;

import human_resources.utility.Utility;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Jelena
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setTitle(Utility.getNameOfApplication());
        jmFile.setText(getTitle());
        new Time().start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnApplicants = new javax.swing.JButton();
        btnJobApplications = new javax.swing.JButton();
        btnJobPositions = new javax.swing.JButton();
        btnTestings = new javax.swing.JButton();
        btnInterviews = new javax.swing.JButton();
        btnJobOffers = new javax.swing.JButton();
        btnOperators = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        lblTime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmFile = new javax.swing.JMenu();
        jmExit = new javax.swing.JMenuItem();
        jmHelp = new javax.swing.JMenu();
        jmAboutProgram = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Programs"));

        btnApplicants.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnApplicants.setText("Applicants");
        btnApplicants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplicantsActionPerformed(evt);
            }
        });

        btnJobApplications.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnJobApplications.setText("Job applications");
        btnJobApplications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobApplicationsActionPerformed(evt);
            }
        });

        btnJobPositions.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnJobPositions.setText("Job positions");
        btnJobPositions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobPositionsActionPerformed(evt);
            }
        });

        btnTestings.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnTestings.setText("Testings");
        btnTestings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestingsActionPerformed(evt);
            }
        });

        btnInterviews.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnInterviews.setText("Interviews");
        btnInterviews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterviewsActionPerformed(evt);
            }
        });

        btnJobOffers.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnJobOffers.setText("Job Offers");
        btnJobOffers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobOffersActionPerformed(evt);
            }
        });

        btnOperators.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnOperators.setText("Operators");
        btnOperators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperatorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOperators, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInterviews, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTestings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnJobPositions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnApplicants, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnJobApplications)
                            .addComponent(btnJobOffers, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnOperators)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApplicants, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnJobApplications, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnJobPositions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTestings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInterviews)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnJobOffers)
                .addGap(21, 21, 21))
        );

        jToolBar1.setRollover(true);

        lblTime.setText("Time");
        jToolBar1.add(lblTime);

        jmFile.setText("File");

        jmExit.setText("Exit");
        jmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmExitActionPerformed(evt);
            }
        });
        jmFile.add(jmExit);

        jMenuBar1.add(jmFile);

        jmHelp.setText("Help");

        jmAboutProgram.setText("About program");
        jmAboutProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAboutProgramActionPerformed(evt);
            }
        });
        jmHelp.add(jmAboutProgram);

        jMenuBar1.add(jmHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmExitActionPerformed
        dispose();
    }//GEN-LAST:event_jmExitActionPerformed

    private void jmAboutProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAboutProgramActionPerformed
        new AboutProgram().setVisible(true);
    }//GEN-LAST:event_jmAboutProgramActionPerformed

    private void btnApplicantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplicantsActionPerformed
        new FormApplicants().setVisible(true);
    }//GEN-LAST:event_btnApplicantsActionPerformed

    private void btnJobApplicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobApplicationsActionPerformed
        new FormJobApplications().setVisible(true);
    }//GEN-LAST:event_btnJobApplicationsActionPerformed

    private void btnJobPositionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobPositionsActionPerformed
        new FormJobPositions().setVisible(true);
    }//GEN-LAST:event_btnJobPositionsActionPerformed

    private void btnTestingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestingsActionPerformed
        new FormTestings().setVisible(true);
    }//GEN-LAST:event_btnTestingsActionPerformed

    private void btnInterviewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterviewsActionPerformed
        new FormInterviews().setVisible(true);
    }//GEN-LAST:event_btnInterviewsActionPerformed

    private void btnJobOffersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobOffersActionPerformed
        new FormJobOffers().setVisible(true);
    }//GEN-LAST:event_btnJobOffersActionPerformed

    private void btnOperatorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperatorsActionPerformed
        new FormOperators().setVisible(true);
    }//GEN-LAST:event_btnOperatorsActionPerformed

    private class Time extends Thread {

        SimpleDateFormat df = new SimpleDateFormat(
                Utility.getFormatDateAndTime());

        @Override
        public void run() {

            lblTime.setText(df.format(new Date()));
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {

            }
            run();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplicants;
    private javax.swing.JButton btnInterviews;
    private javax.swing.JButton btnJobApplications;
    private javax.swing.JButton btnJobOffers;
    private javax.swing.JButton btnJobPositions;
    private javax.swing.JButton btnOperators;
    private javax.swing.JButton btnTestings;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem jmAboutProgram;
    private javax.swing.JMenuItem jmExit;
    private javax.swing.JMenu jmFile;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
